services:
  db:
    image: postgres:15
    container_name: insight-board_postgres_container
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: ${DB_ROOT_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: insight-board_redis_container
    ports:
      - '6379:6379'
